version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run:
          name: Build
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              yarn build
            fi
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn build
            fi
      - persist_to_workspace:
          root: ~/repo
          paths:
            - public/*
  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/node:latest
    steps:
      - run: sudo apt-get update && sudo apt-get install -y python-dev
      - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
      - run: sudo python get-pip.py
      - run: sudo pip install awscli --upgrade
      - run: aws --version
      - attach_workspace:
          at: ~/repo
      - run: ls -aslh
      - run:
          name: Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              aws s3 sync build s3://gwx-token-depot/ --delete
            fi
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync build s3://gwx-token-depot/ --delete
            fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - master
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
                - master
